src/main/java/com/hillel/items_exchange/model/User.java
src/main/resources/liquibase/db.changelog-1.0.xml
src/main/webapp/test.md

Deleted field hometown in the User model and in the table user in the DB, created folder webapp for front end

CGE-48: Deleted field hometown

---

src/main/resources/application.properties

When the application starts from the console using mvn spring-boot:run we could pass the password to the database as a parameter.
The project to run through the terminal team: 
mvn spring-boot:run Dspring-boot.run.arguments=-p=YourPasswordFromBD

CGE-67 Entering the password from the database through the terminal

---

.gitignore
src/main/resources/application.properties

Loggers save information to .log file
All logs have such data: time, message, log level.
1. logging.level - defines the logging level
**logging.level.org.springframework.web=ERROR**
**logging.level.ru.leodev=DEBUG**
2.logging.pattern - defines your own rules (template) of logging
**logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"**
3.logging.file - defines the name of the file to be logged, logs will be written to both the console and the file simultaneously
**logging.file=LogFile.log**

CGE-66 Saving logger information in a separate file

---

src/main/java/com/hillel/items_exchange/controller/AdvertisementController.java
src/main/java/com/hillel/items_exchange/dao/LocationRepository.java
src/main/java/com/hillel/items_exchange/dto/AdvertisementDto.java
src/main/java/com/hillel/items_exchange/model/Product.java
src/main/java/com/hillel/items_exchange/service/AdvertisementService.java
src/main/java/com/hillel/items_exchange/service/LocationService.java
src/test/java/com/hillel/items_exchange/controller/AdvertisementControllerIntegrationTest.java
src/test/java/com/hillel/items_exchange/util/AdvertisementDtoCreatingUtil.java
src/test/resources/datasets/advertisement/update.yml

Fixed advertisement update (child entities updated too)

CGE-90: Fix update advertisement

---

src/main/java/com/hillel/items_exchange/exception/UserValidationException.java
src/test/java/com/hillel/items_exchange/controller/AuthControllerIntegrationTest.java

Changed HTTP status from NOT_ACCEPTABLE to BAD_REQUEST User Validation Exception occurs

CGE-65: Fix NPE when empty JSON is received with registration request

---

src/main/java/com/hillel/items_exchange/dao/UserRepository.java
src/main/java/com/hillel/items_exchange/dto/UserLoginDto.java
src/main/java/com/hillel/items_exchange/service/UserService.java
src/test/java/com/hillel/items_exchange/controller/AuthControllerIntegrationTest.java
src/test/java/com/hillel/items_exchange/util/AuthControllerIntegrationTestUtil.java
src/test/resources/datasets/auth/login.yml

Fixed authentication bug.
BCryptPasswordEncoder coding result every time is different because of salt. So it was problem in comparing of stored in db password and result of BCryptPasswordEncoder coding in straight. Using method 'matches' of BCryptPasswordEncoder solved the problem.

CGE-112 Fixed authentication bug

---

src/main/java/com/hillel/items_exchange/controller/LocationController.java
src/main/java/com/hillel/items_exchange/dao/LocationRepository.java
src/main/java/com/hillel/items_exchange/dto/LocationDto.java
src/main/java/com/hillel/items_exchange/mapper/UtilMapper.java
src/main/java/com/hillel/items_exchange/model/Location.java
src/main/java/com/hillel/items_exchange/service/AdvertisementService.java
src/main/java/com/hillel/items_exchange/service/LocationService.java
src/main/java/com/hillel/items_exchange/service/UserService.java
src/main/java/com/hillel/items_exchange/service/impl/LocationServiceImpl.java
src/main/resources/liquibase/db.changelog-1.0.xml
src/test/java/com/hillel/items_exchange/controller/LocationControllerIntegrationTest.java
src/test/java/com/hillel/items_exchange/service/LocationServiceTest.java
src/test/java/com/hillel/items_exchange/util/LocationDtoCreatingUtil.java
src/test/resources/datasets/location/create.yml
src/test/resources/datasets/location/delete.yml
src/test/resources/datasets/location/update.yml

Created REST endpoint '/location' that will provide access to CRUD operation with it.
Only registered users could use this endpoint.
New code is covered by unit tests.

CGE-105 Create CRUD endpoint for Location

---

src/main/java/com/hillel/items_exchange/dto/LocationDto.java

Added Swagger annotation to show required field `city` correctly

CGE-128 Required field display fix in Swagger 

---

src/main/java/com/hillel/items_exchange/exception/handler/GlobalExceptionHandler.java
src/test/java/com/hillel/items_exchange/controller/LocationControllerIntegrationTest.java
src/test/java/com/hillel/items_exchange/controller/UserControllerTest.java
src/test/java/com/hillel/items_exchange/exceptionshandling/GlobalExceptionHandlerTest.java

Handling of AccessDeniedException was returning 409 status, now it returns default status codes.

CGE-127 Removed AccessDeniedException handling

---

src/main/resources/liquibase/db.changelog-1.1.xml
src/main/resources/liquibase/db.changelog-master.xml

CGE-132: Updated DB structure for further chats implementation

CGE-132: Updated DB structure for further chats implementation

---

src/test/java/com/hillel/items_exchange/controller/AuthControllerIntegrationTest.java

Cge 106 possibility to logout

---

src/main/java/com/hillel/items_exchange/mapper/UserMapper.java

CGE-88 Update personal information

---

src/main/java/com/hillel/items_exchange/dto/ProductDto.java

Fixed bugs in ProductDTO according to task [Jira CGE-117](https://jira.hillel.it/projects/CGE/issues/CGE-117). Fields Age, Gender, Season, Size marked as obligatory, changed annotations.

Cge 117 bug fixes product dto

---

src/main/java/com/hillel/items_exchange/dto/UserDto.java
src/main/java/com/hillel/items_exchange/mapper/UserMapper.java
src/main/java/com/hillel/items_exchange/model/User.java
src/main/resources/liquibase/db.changelog-1.0.xml
src/test/java/com/hillel/items_exchange/util/UserDtoCreatingUtil.java
src/test/resources/datasets/advertisement/create.yml
src/test/resources/datasets/advertisement/delete.yml
src/test/resources/datasets/advertisement/setDefaultImage.yml
src/test/resources/datasets/advertisement/update.yml
src/test/resources/datasets/auth/login.yml
src/test/resources/datasets/auth/register_user.yml
src/test/resources/datasets/children/create.yml
src/test/resources/datasets/children/delete.yml
src/test/resources/datasets/children/update.yml
src/test/resources/datasets/database_init.yml
src/test/resources/datasets/image/delete.yml
src/test/resources/datasets/location/create.yml
src/test/resources/datasets/location/delete.yml
src/test/resources/datasets/location/update.yml
src/test/resources/datasets/security/create_for_security.yml
src/test/resources/datasets/user/update.yml
src/test/resources/datasets/user/update_init.yml

Changed field avatar_image from String to byte[]. Fixed relevant tests. Changed field type in db from varchar to mediumblob via liquibase. Changed users in yml files.

CGE-137 Liquibase changeset image

---

src/main/java/com/hillel/items_exchange/dto/ChildDto.java

Children's data is updated in PUT endpoint after after not filling all required form fields
[Jira bug](https://jira.hillel.it/browse/CGE-120)

CGE-120 ChildDto.birthDate is required

---

src/main/java/com/hillel/items_exchange/controller/AdvertisementController.java
src/test/java/com/hillel/items_exchange/exceptionshandling/GlobalExceptionHandlerTest.java

It was decided to change error from 409 to 403 when an invalid owner wants to update or delete advertisement

Cge 123 error 409 instead error 400 in requests post/put

---

src/main/java/com/hillel/items_exchange/controller/AdvertisementController.java
src/main/java/com/hillel/items_exchange/dto/AdvertisementTitleDto.java
src/main/java/com/hillel/items_exchange/service/AdvertisementService.java
src/main/java/com/hillel/items_exchange/service/impl/AdvertisementServiceImpl.java
src/test/java/com/hillel/items_exchange/controller/AdvertisementControllerTest.java

- Created new class AdvertisementTitleDto;
- Created new endpoint '/adv/thumbnail' to retrieve such dtos;

CGE-121_Implement_AdvertisementTitleDto

---

src/main/java/com/hillel/items_exchange/dto/LocationDto.java
src/main/java/com/hillel/items_exchange/model/Location.java
src/main/java/com/hillel/items_exchange/model/enums/AgeRange.java
src/main/java/com/hillel/items_exchange/model/enums/I18n.java
src/main/resources/liquibase/db.changelog-1.0.xml
src/test/java/com/hillel/items_exchange/service/LocationServiceTest.java
src/test/java/com/hillel/items_exchange/util/AdvertisementDtoCreatingUtil.java
src/test/java/com/hillel/items_exchange/util/LocationDtoCreatingUtil.java
src/test/resources/datasets/advertisement/create.yml
src/test/resources/datasets/advertisement/delete.yml
src/test/resources/datasets/advertisement/setDefaultImage.yml
src/test/resources/datasets/advertisement/update.yml
src/test/resources/datasets/advertisement/updateAdvLocation.yml
src/test/resources/datasets/auth/register_user.yml
src/test/resources/datasets/database_init.yml
src/test/resources/datasets/image/delete.yml
src/test/resources/datasets/location/create.yml
src/test/resources/datasets/location/delete.yml
src/test/resources/datasets/location/update.yml
src/test/resources/datasets/user/update.yml

Added String values to the AgeRange, renamed FROM_13_TO_14 to FROM_12_TO_14, fixed tests.
Renamed Lang to I18n, fixed tests.

Cge 166 db adv entity update

---

src/main/java/com/hillel/items_exchange/model/Phone.java

Removed field 'show' from Phone entity.
Changed type of field 'defaultPhone' to boolean (primitive).

CGE-152: Removed field 'show' from Phone entity.

---

pom.xml
src/main/java/com/hillel/items_exchange/controller/LocationController.java
src/main/java/com/hillel/items_exchange/exception/handler/GlobalExceptionHandler.java
src/main/java/com/hillel/items_exchange/model/Chat.java
src/main/java/com/hillel/items_exchange/model/Message.java
src/main/java/com/hillel/items_exchange/model/User.java
src/main/java/com/hillel/items_exchange/service/impl/LocationServiceImpl.java
src/test/java/com/hillel/items_exchange/chat/ChatEntityTest.java
src/test/java/com/hillel/items_exchange/chat/MessageEntityTest.java
src/test/java/com/hillel/items_exchange/controller/AdvertisementControllerTest.java
src/test/java/com/hillel/items_exchange/controller/AuthControllerIntegrationTest.java
src/test/java/com/hillel/items_exchange/controller/CategoryControllerIntegrationTest.java
src/test/java/com/hillel/items_exchange/controller/LocationControllerIntegrationTest.java
src/test/java/com/hillel/items_exchange/controller/SubcategoryControllerIntegrationTest.java
src/test/java/com/hillel/items_exchange/end2end/AdvertisementFlowTest.java
src/test/java/com/hillel/items_exchange/end2end/ImageFlowTest.java
src/test/java/com/hillel/items_exchange/end2end/UserFlowTest.java
src/test/java/com/hillel/items_exchange/exceptionshandling/GlobalExceptionHandlerTest.java
src/test/java/com/hillel/items_exchange/security/SecurityConfigIntegrationTest.java
src/test/java/com/hillel/items_exchange/service/LocationServiceTest.java

[OBMIN-000] Fixed test for Java 11.0.10 version. Uplifted dependencies

---

src/main/java/space/obminyashka/items_exchange/controller/error/RedirectErrorController.java
src/main/java/space/obminyashka/items_exchange/security/jwt/JwtAuthenticationEntryPoint.java
src/test/java/space/obminyashka/items_exchange/security/SecurityConfigIntegrationTest.java

[OBMIN-3] Fixed 401 code which was cause of 505 code response

---

src/main/java/space/obminyashka/items_exchange/controller/CategoryController.java
src/test/java/space/obminyashka/items_exchange/controller/CategoryControllerIntegrationTest.java
src/test/java/space/obminyashka/items_exchange/util/CategoryTestUtil.java

Fixed by adding "@Valid" to the methods create and update

Obmin 19 add validation in category controller

---

pom.xml
src/main/resources/react/package.json
src/main/resources/react/src/pages/UserInfo/tab_pages/exit/exit.js

OBMIN-6: fixed of page

---

src/main/resources/react/src/pages/ErrorPages/errorPage.scss

Исправление стилей кнопок на странице 404

OBMIN-28: fixed buttons on 404 page

---

pom.xml

* [obmin-01_snapshot] Set release version
* Obmin 44 heroku deploy (#231)
* [obmin-01_snapshot] Set release version (#227)
* [OBMIN-44] Added properties for Heroku deploy
* [OBMIN-44] Added Spring Boot configuration for Heroku deploy
* [OBMIN-44] Updated Liquibase change sets for PostgresSQL compatibility
* OBMIN-22: bugfix
* OBMIN-22: added popup in settings and profile
* OBMIN-22: translated message
* OBMIN-22: changed node
* OBMIN-22: bug fix all
* OBMIN-22: changed node version
Co-authored-by: Roman_Kyrychenko <rp.kyrychenko@gmail.com>
Co-authored-by: Roman Kyrychenko <37712692+rpkyrych@users.noreply.github.com>

Obmin 22 bug fix (#240)

---

src/main/java/space/obminyashka/items_exchange/model/Advertisement.java
src/main/java/space/obminyashka/items_exchange/model/Image.java

Added BinaryType to Lob columns to fix bug when Postgres DB parses SQL

OBMIN-67: Fixed bug when Postgres DB parses SQL

---

src/main/resources/react/src/REST/Service/networkProvider.js
src/main/resources/react/src/components/common/title_Big_Blue/styles.js
src/main/resources/react/src/components/common/title_Big_Blue/title_Big_Blue.jsx
src/main/resources/react/src/components/item-card/ProductCard.jsx
src/main/resources/react/src/pages/UserInfo/tab_pages/my_activity/index.jsx
src/main/resources/react/src/pages/UserInfo/tab_pages/my_activity/styles.js

Change CSS post processor to styled-component (file My_activity)

[OBMIN-99] Change CSS processor to Styled-Component

---

src/main/resources/react/src/pages/homepage/сurrentOffers/index.jsx

To delete Advanced Search from Main Page

OBMIN-52 deleted link

---

src/main/resources/react/src/components/header/nav_category/index.jsx
src/main/resources/react/src/components/header/nav_category/styles.js

Change CSS to Style-components (components-navcategory)

[OBMIN-121] Changed CSS to Styled-components

---

src/main/resources/react/src/components/header/nav_top/index.jsx
src/main/resources/react/src/components/header/nav_top/styles.js

Changed CSS to Styled-components ( Components - Nav_Top)

[OBMIN-119] Changed CSS to Styled-components

---

src/main/resources/react/src/components/header/index.jsx
src/main/resources/react/src/components/header/styles.js

Changed CSS to Styled-components ( file Navbar)

[OBMIN-118] Changed CSS to Styled-components 

---

src/main/resources/react/src/components/common/buttons/buttonAdv/style_button_adv.js
src/main/resources/react/src/components/header/nav_main/index.jsx
src/main/resources/react/src/components/header/nav_main/styles.js

Changed CSS to Styled-components ( Components - Nav_Main)

[OBMIN-120] Changed CSS to Styled-components 

---

src/main/resources/react/src/REST/Service/networkProvider.js
src/main/resources/react/src/components/common/formik/formik-handler/index.jsx
src/main/resources/react/src/components/common/formik/index.js
src/main/resources/react/src/components/common/index.js
src/main/resources/react/src/pages/AddGoods/AddGoods.jsx
src/main/resources/react/src/pages/AddGoods/config.js
src/main/resources/react/src/pages/AddGoods/description/index.jsx
src/main/resources/react/src/pages/AddGoods/description/styles.js
src/main/resources/react/src/pages/AddGoods/drop-down-input/styles.js
src/main/resources/react/src/pages/AddGoods/location/index.jsx
src/main/resources/react/src/pages/AddGoods/location/input-location/index.jsx
src/main/resources/react/src/pages/AddGoods/styles.js
src/main/resources/react/src/store/adv/slice.js

Added count for text area no more 255 symbols
field location is required

Obmin 191 count for textarea

---

README.md
src/main/resources/react/package-lock.json
src/main/resources/react/package.json
src/main/resources/react/src/pages/UserInfo/tab_pages/my_settings/index.jsx

changed button size on the settings page
completely removed sass

[OBMIN-197] changed button size

---

src/main/resources/react/src/config/index.js
src/main/resources/react/src/pages/FormRegister/sign-up/config.js
src/main/resources/react/src/pages/FormRegister/sign-up/index.jsx
src/main/resources/react/src/pages/UserInfo/tab_pages/my_settings/config.js

OBMIN-148 fixed regexp email

---

src/main/resources/react/package-lock.json
src/main/resources/react/package.json
src/main/resources/react/src/components/common/buttons/buttonAdv/index.jsx
src/main/resources/react/src/components/common/buttons/buttonAdv/styles.js
src/main/resources/react/src/pages/AddGoods/AddGoods.jsx
src/main/resources/react/src/pages/AddGoods/photo-files/index.jsx

fixed bug when adding the same file
added file compression

Obmin 198 bugfix upload photo

---

src/main/java/space/obminyashka/items_exchange/dto/AdvertisementDisplayDto.java
src/main/java/space/obminyashka/items_exchange/dto/AdvertisementFilterDto.java
src/main/java/space/obminyashka/items_exchange/dto/AdvertisementModificationDto.java

[OBMIN-205] Changed the field name according to FE model

---

src/main/resources/react/src/Utils/constants.js
src/main/resources/react/src/Utils/convertToMB.js
src/main/resources/react/src/Utils/index.js
src/main/resources/react/src/pages/AddGoods/photo-files/index.jsx
src/main/resources/react/src/pages/UserInfo/active_profile/crop-image/index.jsx

Show errors when we try to add a photo
added file compression

OBMIN-217 added errors

---

src/main/resources/react/src/REST/Service/networkProvider.js
src/main/resources/react/src/Utils/storage.js
src/main/resources/react/src/components/common/pop-up/modal.jsx
src/main/resources/react/src/components/header/nav_top/index.jsx
src/main/resources/react/src/pages/ProductPage/ProductPage.jsx
src/main/resources/react/src/pages/UserInfo/UserInfo.jsx
src/main/resources/react/src/pages/UserInfo/active_profile/index.jsx
src/main/resources/react/src/pages/UserInfo/tab_pages/my_profile/about-myself/config.js
src/main/resources/react/src/pages/UserInfo/tab_pages/my_profile/about-myself/index.jsx
src/main/resources/react/src/pages/UserInfo/tab_pages/my_profile/children/index.jsx
src/main/resources/react/src/pages/UserInfo/tab_pages/my_profile/index.jsx
src/main/resources/react/src/store/auth/slice.js
src/main/resources/react/src/store/profile/slice.js
src/main/resources/react/src/store/ui/slice.js

added default language
fixed profile slice
fixed not required request

Obmin 82 language

---

src/main/resources/react/src/REST/Service/networkProvider.js
src/main/resources/react/src/app/App.jsx
src/main/resources/react/src/components/common/index.js
src/main/resources/react/src/components/common/search-context/index.jsx
src/main/resources/react/src/components/header/nav_main/index.jsx
src/main/resources/react/src/components/header/nav_main/styles.js
src/main/resources/react/src/pages/ProductPage/ProductPage.jsx
src/main/resources/react/src/pages/SearchResults/index.jsx

added the ability to make a search request
fixed wishes on the product page

Obmin 226 search bar

---

src/main/resources/react/src/components/common/filtration/input/styles.js
src/main/resources/react/src/pages/UserInfo/tab_pages/my_profile/about-myself/config.js

I also corrected the sizes of the blocks in accordance with the layout on the page with 'search results'

[OBMIN-220] The ability to add numbers in the Name and Last name fields

---

src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java
src/main/resources/react/src/components/common/formik/formik-focus/index.jsx
src/main/resources/react/src/components/common/formik/index.js
src/main/resources/react/src/components/local/en.js
src/main/resources/react/src/pages/AddGoods/AddGoods.jsx
src/main/resources/react/src/pages/AddGoods/exchange/index.jsx
src/main/resources/react/src/pages/AddGoods/location/index.jsx
src/main/resources/react/src/pages/AddGoods/photo-files/index.jsx
src/main/resources/react/src/pages/AddGoods/selection-section/index.jsx
src/main/resources/react/src/pages/AddGoods/show-select-item/index.jsx
src/main/resources/react/src/pages/AddGoods/sizes/index.jsx
src/main/resources/react/src/pages/AddGoods/wrap-characteristic/index.jsx

Added the ability to focus on errors, commented out the line with hashing, changed the name of the "Add new advertisement" button to "Add advertisement" for english version

[OBMIN-224] Error handling

---

src/main/resources/react/src/pages/SearchResults/index.jsx
src/main/resources/react/src/store/profile/thunk.js

added correct behavior to search 
remove popup at home with error 401

OBMIN-233 fixed popup at home page

---

.github/workflows/node.js.yml
Dockerfile
nginx/Dockerfile
pom.xml

- Updated NodeJS to the latest LTS version
- updated docker images for NodeJS supportability
- uplifted some project's dependencies

[NO_JIRA] Updated nodejs to the latest LTS version

---

src/main/resources/react/src/REST/Resources/add-good.js
src/main/resources/react/src/REST/Resources/profile.js

Fixed adding avatar after updating dependencies

fixed formdata in request

---

src/main/java/space/obminyashka/items_exchange/controller/CategoryController.java
src/main/java/space/obminyashka/items_exchange/exception/CategorySizeNotFoundException.java
src/main/java/space/obminyashka/items_exchange/exception/NotFoundException.java
src/main/java/space/obminyashka/items_exchange/util/ResponseMessagesHandler.java
src/main/resources/messages.properties
src/test/java/space/obminyashka/items_exchange/end2end/CategoryFlowTest.java

added message: "Sizes are available only for the categories… "Clothes" and "Shoes""

OBMIN-253 

---

src/main/resources/react/package-lock.json
src/main/resources/react/package.json
src/main/resources/react/src/pages/AddGoods/AddGoods.jsx
src/main/resources/react/src/pages/AddGoods/exchange/index.jsx
src/main/resources/react/src/pages/AddGoods/wrap-characteristic/index.jsx
src/main/resources/react/src/pages/AddGoods/wrap-characteristic/styles.js
src/main/resources/react/src/pages/FormRegister/sign-up/index.jsx

fixed bugs with display icons and placement of checkbox in AddGoods

[OBMIN-294] checkbox_improving

---

src/main/java/space/obminyashka/items_exchange/dto/UserChangePasswordDto.java
src/main/java/space/obminyashka/items_exchange/dto/UserRegistrationDto.java

write examples for fields with pattern

OBMIN-285 write examples for fields with pattern

---

src/main/resources/react/package-lock.json
src/main/resources/react/src/REST/Service/networkProvider.js

Obmin 330 fixed product card

---

src/main/java/space/obminyashka/items_exchange/model/enums/Season.java

- Change ENUM for “Season” filter.
- Rename 1 item ALL_SEASONS to NO_SEASON

Change ENUM for “Season” filter

---

.github/workflows/codeql-analysis.yml
.github/workflows/java-ci.yml
.github/workflows/node.js.yml
README.md
pom.xml
src/main/resources/application.properties

Introduced a new CI Action replacing Jenkins CI
All the build attempts could be found here: https://github.com/Jack11M/obminyashka.space/pull/495

[OBMIN-298] Created and configured GitHub CI Action replacing Jenkins CI

---

src/main/java/space/obminyashka/items_exchange/controller/AdvertisementController.java
src/main/java/space/obminyashka/items_exchange/controller/AuthController.java
src/main/java/space/obminyashka/items_exchange/controller/CategoryController.java
src/main/java/space/obminyashka/items_exchange/controller/ImageController.java
src/main/java/space/obminyashka/items_exchange/controller/LocationController.java
src/main/java/space/obminyashka/items_exchange/controller/SubcategoryController.java
src/main/java/space/obminyashka/items_exchange/controller/UserController.java
src/main/java/space/obminyashka/items_exchange/dto/PhoneDto.java

Update swagger parameter
Add produces to endpoint to get a necessary response
Change example for PhoneDto

OBMIN-332 Update swagger parameter

---

src/main/java/space/obminyashka/items_exchange/dao/UserRepository.java
src/main/java/space/obminyashka/items_exchange/service/UserService.java
src/main/java/space/obminyashka/items_exchange/service/impl/UserServiceImpl.java
src/test/java/space/obminyashka/items_exchange/service/UserServiceIntegrationTest.java
src/test/java/space/obminyashka/items_exchange/service/UserServiceTest.java

set flag "true" if it old user and created account by OAuth2 long time ago

[hotfix/OBMIN-210] creat query for OAuth2 account

---

package-lock.json
src/main/resources/react/package-lock.json
src/main/resources/react/src/pages/AddGoods/AddGoods.jsx
src/main/resources/react/src/pages/AddGoods/styles.js

Move add goods description component

Obmin 331 move add goods description component

---

src/main/java/space/obminyashka/items_exchange/controller/AuthController.java
src/main/java/space/obminyashka/items_exchange/service/MailService.java
src/main/java/space/obminyashka/items_exchange/service/impl/SendGridService.java
src/test/java/space/obminyashka/items_exchange/controller/AuthorizationControllerTest.java
src/test/java/space/obminyashka/items_exchange/service/MailServiceIntegrationTest.java
src/test/java/space/obminyashka/items_exchange/service/MailServiceTest.java

created a full ULR to MailContoller in SendGridService,
refacted test sendMail_shouldPassTheFlow(),
rename method permanentlyDeleteEmailConfirmationToken()

OBMIN-339 Send generated email validation code during registration procedure

---

src/main/resources/react/src/components/header/nav_top/index.jsx
src/main/resources/react/src/components/header/nav_top/styles.js

Obmin 378 redesign component avatar

---

src/main/java/space/obminyashka/items_exchange/controller/AuthController.java
src/main/java/space/obminyashka/items_exchange/controller/LocationController.java
src/main/java/space/obminyashka/items_exchange/controller/UserController.java
src/main/resources/application.properties

OBMIN-365 Swagger improvement v.2. Remove generetic response

OBMIN-365 Swagger improvement v.2. Remove generetic response

---

src/main/java/space/obminyashka/items_exchange/controller/SubcategoryController.java
src/main/java/space/obminyashka/items_exchange/dao/AdvertisementRepository.java
src/main/java/space/obminyashka/items_exchange/dao/SubcategoryRepository.java
src/main/java/space/obminyashka/items_exchange/service/AdvertisementService.java
src/main/java/space/obminyashka/items_exchange/service/SubcategoryService.java
src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java
src/main/java/space/obminyashka/items_exchange/service/impl/SubcategoryServiceImpl.java
src/test/java/space/obminyashka/items_exchange/service/AdvertisementServiceTest.java
src/test/java/space/obminyashka/items_exchange/service/SubcategoryServiceTest.java

rewrote sql query and fixed tests

OBMIN-406 Optimization of SLQ requests to Delete Subcategory By ID API

---

src/main/java/space/obminyashka/items_exchange/model/User.java
src/main/resources/liquibase/db.changelog-1.2.xml
src/test/java/space/obminyashka/items_exchange/service/FavoriteAdvertisementDBTest.java
src/test/java/space/obminyashka/items_exchange/service/UserServiceIntegrationTest.java
src/test/resources/datasets/advertisement/addFavoriteAdv.yml

- created table **favorite_advertisement**
- added new field **favoriteAdvertisements** to User
- added test

[OBMIN-432] Create Favourite advertisement entity and DB structure

---

src/main/java/space/obminyashka/items_exchange/api/ApiKey.java
src/main/java/space/obminyashka/items_exchange/controller/AdvertisementController.java
src/main/java/space/obminyashka/items_exchange/dao/AdvertisementRepository.java
src/main/java/space/obminyashka/items_exchange/service/AdvertisementService.java
src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java
src/test/java/space/obminyashka/items_exchange/controller/AdvertisementControllerIntegrationTest.java
src/test/java/space/obminyashka/items_exchange/end2end/AdvertisementFlowTest.java

OBMIN-450 Remove excess endpoint for searching advertisements with existing category

OBMIN-450 Remove excess endpoint for searching advertisements

---

src/main/java/space/obminyashka/items_exchange/dto/PhoneDto.java
src/test/java/space/obminyashka/items_exchange/controller/UserControllerIntegrationTest.java
src/test/java/space/obminyashka/items_exchange/util/UserDtoCreatingUtil.java

changes:
- wrote test
- added annotation NotNull to field with number

OBMIN-407 fixed bug with null phone number

---

src/main/java/space/obminyashka/items_exchange/api/ApiKey.java
src/main/java/space/obminyashka/items_exchange/controller/UserController.java
src/main/java/space/obminyashka/items_exchange/dao/AdvertisementRepository.java
src/main/java/space/obminyashka/items_exchange/service/AdvertisementService.java
src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java
src/test/java/space/obminyashka/items_exchange/controller/UserControllerIntegrationTest.java
src/test/java/space/obminyashka/items_exchange/end2end/UserFlowTest.java
src/test/java/space/obminyashka/items_exchange/service/AdvertisementServiceTest.java
src/test/resources/datasets/advertisement/addFavorite.yml
src/test/resources/datasets/advertisement/addNewFavorite.yml

- Create new endpoint for add favorite
- Added tests

OBMIN-433 create new endpoint for add favorite

---

src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java

Committed the annotation @Cacheable so that the endpoint works correctly when adding new ads

OBMIN-403 fix update list adv

---

src/main/java/space/obminyashka/items_exchange/repository/DistrictRepository.java
src/main/java/space/obminyashka/items_exchange/rest/LocationController.java
src/main/java/space/obminyashka/items_exchange/rest/api/ApiKey.java
src/main/java/space/obminyashka/items_exchange/rest/mapper/LocationMapper.java
src/main/java/space/obminyashka/items_exchange/service/LocationService.java
src/main/java/space/obminyashka/items_exchange/service/impl/LocationServiceImpl.java
src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
src/test/java/space/obminyashka/items_exchange/service/LocationServiceTest.java
src/test/resources/datasets/location/location_init.yml

- Create new endpoint to get districts by area id
- Added tests

OBMIN-467  Create new endpoint to get districts by area id

---

docker-compose.yml

changes:
- added configuration in docker-compose for mongodb

Add mongodb into docker

---

src/main/java/space/obminyashka/items_exchange/repository/AdvertisementRepository.java
src/main/java/space/obminyashka/items_exchange/repository/projection/AdvertisementTitleProjection.java
src/main/java/space/obminyashka/items_exchange/rest/mapper/AdvertisementMapper.java
src/main/java/space/obminyashka/items_exchange/rest/response/AdvertisementTitleView.java

changes:
-  added isFavorite field in dto
- added new map method for calculating value of this field
-  rewrote sql for getting additional field (userId)

OBMIN-436 To modify AdvertisementTitleDto with isFavorite marker parameter

---

.github/workflows/codeql-analysis.yml
.github/workflows/java-ci.yml
Dockerfile
docker-compose.yml
nginx/Dockerfile
pom.xml
src/main/java/space/obminyashka/items_exchange/config/AppConfig.java
src/main/java/space/obminyashka/items_exchange/config/SecurityConfig.java
src/main/java/space/obminyashka/items_exchange/repository/AdvertisementRepository.java
src/main/java/space/obminyashka/items_exchange/repository/model/Advertisement.java
src/main/java/space/obminyashka/items_exchange/repository/model/Image.java
src/main/java/space/obminyashka/items_exchange/repository/model/User.java
src/main/resources/application.properties
src/test/resources/application.properties
src/test/resources/dbunit.yml

- uplifted needed dependencies;
- modified entities for the latest version of the Spring framework
- updated Spring Security configuration with new methods instead of deprecated ones
- uplifted Liquibase dependency version to the latest and removed excess code parts once a library bug was fixed within the latest changes

[OBMIN-495] Introduced Java 21 LTS

---

src/main/java/space/obminyashka/items_exchange/config/SecurityConfig.java
src/main/java/space/obminyashka/items_exchange/repository/AdvertisementRepository.java
src/main/java/space/obminyashka/items_exchange/repository/SubcategoryRepository.java
src/main/java/space/obminyashka/items_exchange/rest/AdvertisementController.java
src/main/java/space/obminyashka/items_exchange/rest/api/ApiKey.java
src/main/java/space/obminyashka/items_exchange/rest/request/AdvertisementFilterRequest.java
src/main/java/space/obminyashka/items_exchange/rest/response/message/ResponseMessagesHandler.java
src/main/java/space/obminyashka/items_exchange/service/AdvertisementService.java
src/main/java/space/obminyashka/items_exchange/service/SubcategoryService.java
src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java
src/main/java/space/obminyashka/items_exchange/service/impl/SubcategoryServiceImpl.java
src/main/resources/messages.properties
src/test/java/space/obminyashka/items_exchange/end2end/AdvertisementFlowTest.java
src/test/java/space/obminyashka/items_exchange/rest/AdvertisementControllerIntegrationTest.java

**[OBMIN-451]**: 
- changed error message with a list of available subcategories for the entered categories
- filtering by random is work
**[OBMIN-417]**:
- filter considering excluded adv id is work
**[OBMIN-487]**:
- merched two filtering endpoint for finding adv by all parameters: location, list of category, subcategory, keywords ect

[OBMIN-487] changed the search for advertisement by all parameters

---

frontend/package-lock.json
frontend/package.json
frontend/src/REST/Resources/home.ts
frontend/src/REST/Resources/search.ts
frontend/src/pages/SearchResults/index.tsx
src/main/java/space/obminyashka/items_exchange/rest/AdvertisementController.java

- Fixed request type for random advertisements load on the main page
- Fixed UI search request by using appropriate filter API with passing 'keyword' and request 'page'
- Updated the filter API by removing 404-response code for a more consistent load of the main page

[NO-JIRA] Fixed advertisements load on the main page by using the appripriate API

---

src/main/java/space/obminyashka/items_exchange/repository/AdvertisementRepository.java
src/main/java/space/obminyashka/items_exchange/rest/request/AdvertisementFilterRequest.java
src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java

[OBMIN-515](https://jira.ithillel.com/browse/OBMIN-515) - if categoryId is given, the search will go only on it (this is required for "Categories" in the main page)

[OBMIN-515] added searching by category id

---

src/main/java/space/obminyashka/items_exchange/rest/SubcategoryController.java
src/test/java/space/obminyashka/items_exchange/rest/LocationControllerIntegrationTest.java

OBMIN-511 fix bug with deleating subcategory

OBMIN-511 - fix bug with deleting subcategory
